#include <iostream>
#include <string>
#include <thread>
#include <chrono>

void displayTitle() {
    std::cout << R"(
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  dddddddd
WWWWWWWW                           WWWWWWWW                    lllllll                                                                                                tttt                                         tttt          hhhhhhh                                                                                                            iiii                                                                                                      lllllll             d::::::d
W::::::W                           W::::::W                    l:::::l                                                                                             ttt:::t                                      ttt:::t          h:::::h                                                                                                           i::::i                                                                                                     l:::::l             d::::::d
W::::::W                           W::::::W                    l:::::l                                                                                             t:::::t                                      t:::::t          h:::::h                                                                                                            iiii                                                                                                      l:::::l             d::::::d
W::::::W                           W::::::W                    l:::::l                                                                                             t:::::t                                      t:::::t          h:::::h                                                                                                                                                                                                                      l:::::l             d:::::d 
 W:::::W           WWWWW           W:::::W     eeeeeeeeeeee     l::::l     cccccccccccccccc   ooooooooooo      mmmmmmm    mmmmmmm       eeeeeeeeeeee         ttttttt:::::ttttttt       ooooooooooo        ttttttt:::::ttttttt     h::::h hhhhh           eeeeeeeeeeee        ssssssssss     aaaaaaaaaaaaa   nnnn  nnnnnnnn    rrrrr   rrrrrrrrr   iiiiiii    ooooooooooo        wwwwwww           wwwww           wwwwwww   ooooooooooo   rrrrr   rrrrrrrrr    l::::l     ddddddddd:::::d 
  W:::::W         W:::::W         W:::::W    ee::::::::::::ee   l::::l   cc:::::::::::::::c oo:::::::::::oo  mm:::::::m  m:::::::mm   ee::::::::::::ee       t:::::::::::::::::t     oo:::::::::::oo      t:::::::::::::::::t     h::::hh:::::hhh      ee::::::::::::ee    ss::::::::::s    a::::::::::::a  n:::nn::::::::nn  r::::rrr:::::::::r  i:::::i  oo:::::::::::oo       w:::::w         w:::::w         w:::::w  oo:::::::::::oo r::::rrr:::::::::r   l::::l   dd::::::::::::::d 
   W:::::W       W:::::::W       W:::::W    e::::::eeeee:::::ee l::::l  c:::::::::::::::::co:::::::::::::::om::::::::::mm::::::::::m e::::::eeeee:::::ee     t:::::::::::::::::t    o:::::::::::::::o     t:::::::::::::::::t     h::::::::::::::hh   e::::::eeeee:::::eess:::::::::::::s   aaaaaaaaa:::::a n::::::::::::::nn r:::::::::::::::::r  i::::i o:::::::::::::::o       w:::::w       w:::::::w       w:::::w  o:::::::::::::::or:::::::::::::::::r  l::::l  d::::::::::::::::d 
    W:::::W     W:::::::::W     W:::::W    e::::::e     e:::::e l::::l c:::::::cccccc:::::co:::::ooooo:::::om::::::::::::::::::::::me::::::e     e:::::e     tttttt:::::::tttttt    o:::::ooooo:::::o     tttttt:::::::tttttt     h:::::::hhh::::::h e::::::e     e:::::es::::::ssss:::::s           a::::a nn:::::::::::::::nrr::::::rrrrr::::::r i::::i o:::::ooooo:::::o        w:::::w     w:::::::::w     w:::::w   o:::::ooooo:::::orr::::::rrrrr::::::r l::::l d:::::::ddddd:::::d 
     W:::::W   W:::::W:::::W   W:::::W     e:::::::eeeee::::::e l::::l c::::::c     ccccccco::::o     o::::om:::::mmm::::::mmm:::::me:::::::eeeee::::::e           t:::::t          o::::o     o::::o           t:::::t           h::::::h   h::::::he:::::::eeeee::::::e s:::::s  ssssss     aaaaaaa:::::a   n:::::nnnn:::::n r:::::r     r:::::r i::::i o::::o     o::::o         w:::::w   w:::::w:::::w   w:::::w    o::::o     o::::o r:::::r     r:::::r l::::l d::::::d    d:::::d 
      W:::::W W:::::W W:::::W W:::::W      e:::::::::::::::::e  l::::l c:::::c             o::::o     o::::om::::m   m::::m   m::::me:::::::::::::::::e            t:::::t          o::::o     o::::o           t:::::t           h:::::h     h:::::he:::::::::::::::::e    s::::::s        aa::::::::::::a   n::::n    n::::n r:::::r     rrrrrrr i::::i o::::o     o::::o          w:::::w w:::::w w:::::w w:::::w     o::::o     o::::o r:::::r     rrrrrrr l::::l d:::::d     d:::::d 
       W:::::W:::::W   W:::::W:::::W       e::::::eeeeeeeeeee   l::::l c:::::c             o::::o     o::::om::::m   m::::m   m::::me::::::eeeeeeeeeee             t:::::t          o::::o     o::::o           t:::::t           h:::::h     h:::::he::::::eeeeeeeeeee        s::::::s    a::::aaaa::::::a   n::::n    n::::n r:::::r             i::::i o::::o     o::::o           w:::::w:::::w   w:::::w:::::w      o::::o     o::::o r:::::r             l::::l d:::::d     d:::::d 
        W:::::::::W     W:::::::::W        e:::::::e            l::::l c::::::c     ccccccco::::o     o::::om::::m   m::::m   m::::me:::::::e                      t:::::t    tttttto::::o     o::::o           t:::::t    tttttt h:::::h     h:::::he:::::::e           ssssss   s:::::s a::::a    a:::::a   n::::n    n::::n r:::::r             i::::i o::::o     o::::o            w:::::::::w     w:::::::::w       o::::o     o::::o r:::::r             l::::l d:::::d     d:::::d 
         W:::::::W       W:::::::W         e::::::::e          l::::::lc:::::::cccccc:::::co:::::ooooo:::::om::::m   m::::m   m::::me::::::::e                     t::::::tttt:::::to:::::ooooo:::::o           t::::::tttt:::::t h:::::h     h:::::he::::::::e          s:::::ssss::::::sa::::a    a:::::a   n::::n    n::::n r:::::r            i::::::io:::::ooooo:::::o             w:::::::w       w:::::::w        o:::::ooooo:::::o r:::::r            l::::::ld::::::ddddd::::::dd
          W:::::W         W:::::W           e::::::::eeeeeeee  l::::::l c:::::::::::::::::co:::::::::::::::om::::m   m::::m   m::::m e::::::::eeeeeeee             tt::::::::::::::to:::::::::::::::o           tt::::::::::::::t h:::::h     h:::::h e::::::::eeeeeeee  s::::::::::::::s a:::::aaaa::::::a   n::::n    n::::n r:::::r            i::::::io:::::::::::::::o              w:::::w         w:::::w         o:::::::::::::::o r:::::r            l::::::l d:::::::::::::::::d
           W:::W           W:::W             ee:::::::::::::e  l::::::l  cc:::::::::::::::c oo:::::::::::oo m::::m   m::::m   m::::m  ee:::::::::::::e               tt:::::::::::tt oo:::::::::::oo              tt:::::::::::tt h:::::h     h:::::h  ee:::::::::::::e   s:::::::::::ss   a::::::::::aa:::a  n::::n    n::::n r:::::r            i::::::i oo:::::::::::oo                w:::w           w:::w           oo:::::::::::oo  r:::::r            l::::::l  d:::::::::ddd::::d
            WWW             WWW                eeeeeeeeeeeeee  llllllll    cccccccccccccccc   ooooooooooo   mmmmmm   mmmmmm   mmmmmm    eeeeeeeeeeeeee                 ttttttttttt     ooooooooooo                  ttttttttttt   hhhhhhh     hhhhhhh    eeeeeeeeeeeeee    sssssssssss      aaaaaaaaaa  aaaa  nnnnnn    nnnnnn rrrrrrr            iiiiiiii   ooooooooooo                   www             www              ooooooooooo    rrrrrrr            llllllll   ddddddddd   ddddd
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          
    )" << std::endl;
}

void startGame() {
    std::cout << "Press [Enter] to start your adventure..." << std::endl;
    std::cin.get();
    std::cout << "Loading your adventure..." << std::endl;
    std::this_thread::sleep_for(std::chrono::seconds(2));
}

int main() {
    displayTitle();
    startGame();
    std::cout << "Your adventure begins here!" << std::endl;
    return 0;
}
